title: OIPD Documentation
description: Options Implied Probability Distribution

remote-theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

just_the_docs:
  search_enabled: true