title: OIPD Documentation
description: Options Implied Probability Distribution
remote-theme: just-the-docs

# GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

just_the_docs:
  search_enabled: true
